In [146]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [2]:
dataset=pd.read_csv(r"E:\tops\Data science\machine Learning\confusion Matrix\Multiple_input.csv")
dataset.head(3)

Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0

In [3]:
dataset.drop("Unnamed: 0", axis=1, inplace=True)


In [4]:
dataset.head(3)

cgpa     iq  placement
0   6.8  123.0          1
1   5.9  106.0          0
2   5.3  121.0          0

In [5]:
from sklearn.model_selection import train_test_split

In [178]:
x=dataset.iloc[:,:-1]
#x=dataset[["cgpa"]]
y=dataset["placement"]


In [23]:
x.shape

(100, 2)

In [179]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=64)

In [136]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()


In [137]:
lr.fit(x_train,y_train)

LogisticRegression()

In [138]:
lr.score(x_test,y_test)*100

95.0

In [166]:
from sklearn.metrics import confusion_matrix ,precision_score,f1_score,recall_score

In [139]:
confusion_matrix(y_test,lr.predict(x_test))

array([[ 8,  0],
       [ 1, 11]])

In [140]:
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0])

In [104]:
x_test

cgpa     iq
42   7.6   89.0
54   6.4  141.0
27   6.0  124.0
93   6.8  112.0
39   4.6  146.0
65   8.1  166.0
7    5.0   63.0
26   7.0  199.0
24   4.7  121.0
60   6.9  139.0
86   5.1  128.0
30   7.6  128.0
37   8.1  149.0
70   6.3  127.0
19   5.2  132.0
99   6.2  113.0
96   4.4   42.0
33   6.0  149.0
66   6.9   96.0
68   4.0   75.0

In [127]:
import numpy as np

 

# गलत rows निकालना
wrong_indices = np.where(y_test != y_pred)[0]
print("गलत rows:", wrong_indices)



गलत rows: [10]


In [ ]:
22    0

22 	4.9 	120.0

In [128]:
precision = precision_score(y_test, y_pred)*100
recall = recall_score(y_test, y_pred)*100
f1 = f1_score(y_test, y_pred)*100

print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 100.0
Recall: 88.88888888888889
F1-Score: 94.11764705882352


In [141]:
precision = precision_score(y_test, y_pred)*100
recall = recall_score(y_test, y_pred)*100
f1 = f1_score(y_test, y_pred)*100

print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 100.0
Recall: 91.66666666666666
F1-Score: 95.65217391304348


In [169]:
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],       # अलग-अलग regularization strength
    'solver': ['liblinear', 'lbfgs'],   # optimization algorithms
    'penalty': ['l1', 'l2']             # regularization type
}


In [180]:
grid = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid.fit(x_train, y_train)

E:\app\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
E:\app\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
E:\app\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
E:\app\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
E:\app\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
E:\app\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
E:\app\anaconda3

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear', 'lbfgs']})

In [181]:
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1])

In [182]:
precision = precision_score(y_test, y_pred)*100
recall = recall_score(y_test, y_pred)*100
f1 = f1_score(y_test, y_pred)*100

print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 100.0
Recall: 100.0
F1-Score: 100.0


In [184]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(lr, x, y, cv=5, scoring='f1_macro')
print("Cross-validation F1 scores:", scores)
print("Mean F1:", np.mean(scores))


Cross-validation F1 scores: [0.84962406 0.94987469 0.94987469 0.84654731 0.8989899 ]
Mean F1: 0.8989821294303729


In [185]:
l = [10, "hello", 20, "wold"]

i = [x for x in l if isinstance(x, int)]
s = [x for x in l if isinstance(x, str)]

print(i)
print(s)


[10, 20]
['hello', 'wold']
