In [1]:
import pandas as pd

In [53]:
dataset=pd.read_csv(r"E:\tops\Data science\machine Learning\loan.csv")
dataset.head(3)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   
1  LP001003   Male     Yes          1  Graduate            No   
2  LP001005   Male     Yes          0  Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y

In [54]:
dataset.shape

(614, 13)

In [7]:
ar=list(dataset["Property_Area"].unique())  #unique value store ar variable

In [13]:
def get_dim(lst):
    if isinstance(lst, list):
        return 1 + get_dim(lst[0])
    else:
        return 0


   # Output: 2


In [14]:
print(get_dim(ar))


2


# scikit learn library through Encoding OrdinalEncoder

In [4]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
ord1=OrdinalEncoder(categories=ar)   #ordinal Encoder coll

In [16]:
ord1.fit(dataset[["Property_Area"]])   #model fit

OrdinalEncoder(categories=[['Urban', 'Rural', 'Semiurban']])

In [30]:
lt=ord1.fit_transform(dataset[["Property_Area"]]) # model fit transfor both tugather

In [56]:
lt

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],

In [28]:
type(lt)

numpy.ndarray

In [33]:
dataset["Property_Area"]=lt                      #origanl data set change encoding

In [35]:
dataset["Property_Area"].unique()

array([0., 1., 2.])

In [36]:
dataset.head(3)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   
1  LP001003   Male     Yes          1  Graduate            No   
2  LP001005   Male     Yes          0  Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   

   Credit_History  Property_Area Loan_Status  
0             1.0            0.0           Y  
1             1.0            1.0           N  
2             1.0            0.0           Y

# map function through encoding

In [47]:
l1=list(dataset["Property_Area"].unique())                   # list 1 create 
l2=[]
l2=list((i for i in range(len(l1))))                         # using list comprasion list 2 create   

In [48]:
data=dict(zip(l1,l2))                                      # list to dict convert 

In [49]:
data

{'Urban': 0, 'Rural': 1, 'Semiurban': 2}

In [50]:
dataset["Property_Area"]=dataset["Property_Area"].map(data)          #origanal data in change 

In [51]:
dataset["Property_Area"].unique()

array([0, 1, 2])

In [52]:
dataset

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History  Property_Area Loan_Status  
0               1.0              0           Y  
1               1.0              1           N  
2               1.0              0           Y  
3               1.0              0           Y  
4               1.0              0           Y  
..              ...            ...         ...  
609             1.0              1           Y  
610             1.0              1           Y  
611             1.0              0           Y  
612             1.0              0           Y  
613             0.0              2           N  

[614 rows x 13 columns]